export const projectsData = [
  {
    id: 1,
    title: "Cinema Watchlist",
    url: "https://cinema-watchlist.herokuapp.com/welcomes/home",
    image: "",
    category: "Rails",
    description:
      "Simple website in which a user can access to create watch list from various movies.",
    source: "https://github.com/Wolfinbarger/rails-watch-list#-watchlist",
    tags: [
      "devicon-html5-plain",
      "devicon-sass-original",
      "devicon-bootstrap-plain",
      "devicon-javascript-plain",
      "devicon-ruby-plain",
      "devicon-rails-plain",
      "devicon-postgresql-plain",
    ],
  },
  {
    id: 2,
    title: "Blork's Used Spaceship Emporium",
    url: "https://blorks-used-spaceships.herokuapp.com",
    image: "",
    category: "Rails",
    description:
      "Spaceship rental website. In which a user can rent or rent out a spaceship that for a set period of time.",
    source: "https://github.com/Wolfinbarger/UsedShips",
    tags: [
      "devicon-html5-plain",
      "devicon-sass-original",
      "devicon-javascript-plain",
      "devicon-ruby-plain",
      "devicon-rails-plain",
      "devicon-postgresql-plain",
    ],
  },
  {
    id: 3,
    title: "Word Quest",
    url: "https://www.wordquest.app",
    image: "",
    category: "Rails",
    description:
      "An interactive English learning web application. In which a person will set out on a quest to improve their language ability while leveling up their character.",
    source: "https://github.com/DanielBScharf/word_quest",
    tags: [
      "devicon-html5-plain",
      "devicon-sass-original",
      "devicon-javascript-plain",
      "devicon-ruby-plain",
      "devicon-rails-plain",
      "devicon-postgresql-plain",
    ],
  },
  {
    id: 4,
    title: "Sushi World",
    url: "https://demosushi.fun",
    image: "",
    category: "Website",
    description: "Japanese sushi restaurant display food that is provided.",
    source: "https://github.com/DanielBScharf/word_quest",
    tags: [
      "devicon-html5-plain",
      "devicon-css3-original",
      "devicon-javascript-plain",
    ],
  },
];
